-- Indexes the change event stream's poll.
--
-- Every open SSE connection re-reads its change's events every 2 seconds. The
-- only index on `events` was `sqlite_autoindex_events_1` over the TEXT primary
-- key, which a `WHERE change_id = ?` lookup cannot use, so each of those polls
-- was a full table scan reading every column of every row -- `raw_json`
-- included -- to decide whether anything new had arrived. The cost therefore
-- grew with the size of the whole table rather than with the one change being
-- watched, on a table that only grows. The logs show 306 stream opens with a
-- longest single connection of 96.4 minutes, i.e. ~2900 such scans from one
-- browser tab.
--
-- Column order follows the query: equality on `change_id` first, then
-- `created_at, id` to serve the ORDER BY. Including `id` (already implicit as
-- the rowid lookup key, but named here so the ordering is total and the index
-- covers it) lets the poll read ids straight out of the index without touching
-- the table at all.
--
-- Deliberately not UNIQUE: (change_id, created_at, id) is unique in practice
-- because id is the primary key, but declaring it so would add a constraint
-- this index exists only to accelerate.
CREATE INDEX IF NOT EXISTS `idx_events_change_created_id` ON `events` (`change_id`,`created_at`,`id`);
