import fs from "node:fs";
import os from "node:os";
import path from "node:path";

/**
 * A CODEX_HOME that inherits the user's Codex except for the plugins it loads.
 *
 * ## Why this exists
 *
 * A stage that expects the model to answer in a line protocol cannot be handed
 * the StagePass card tools: given a card it can call and a protocol it was told
 * to write, the model calls the card. That was not hypothetical -- the PRD turn
 * replied "请在审批卡中选择批准或打回" and emitted none of the protocol lines
 * the parser requires.
 *
 * Per-turn `config` overrides cannot switch plugins off (tried, both dotted-key
 * and nested forms; the startup list came back unchanged). CODEX_HOME can, so
 * the choice of home IS the choice of tool surface.
 *
 * ## Why it symlinks nearly everything
 *
 * A home containing only auth would give the isolated stages their own thread
 * store, and threads created there would not appear in Codex Desktop. Every
 * entry is therefore linked back to the real home except the two that must
 * differ, so a turn run under this profile is still a normal thread the user
 * can open. Verified: with the links in place the plugin list is bare and the
 * thread still lands in the shared store.
 *
 * Linking by enumeration rather than by a list of known filenames is deliberate.
 * The thread store is `state_5.sqlite` today and will be `state_6.sqlite` some
 * day; a hardcoded list would silently start giving isolated stages a private
 * store the first time Codex bumped that number.
 */

/** What must NOT be inherited, and why. */
const OVERRIDDEN_ENTRIES = new Set([
  // Ours: it is the file that decides which plugins load.
  "config.toml",
  // Absent on purpose: plugins are discovered from this cache, so a home
  // without it cannot offer them however the config is written.
  "plugins",
]);

export type CodexToolSurface = "full" | "no-stagepass-plugins";

export function defaultCodexHome(env: NodeJS.ProcessEnv = process.env): string {
  return env.CODEX_HOME?.trim() || path.join(os.homedir(), ".codex");
}

/**
 * Materializes the profile and returns the CODEX_HOME to run a turn under.
 *
 * Idempotent and cheap: links are refreshed each call so a Codex upgrade that
 * adds or renames a top-level entry is picked up without anyone remembering to
 * clear a cache.
 */
export function ensureCodexHomeProfile(input: {
  surface: CodexToolSurface;
  baseHome?: string;
  root?: string;
}): string {
  const baseHome = input.baseHome ?? defaultCodexHome();
  if (input.surface === "full") return baseHome;

  const root = input.root
    ?? path.join(os.tmpdir(), "stagepass-codex-homes");
  const home = path.join(root, input.surface);
  fs.mkdirSync(home, { recursive: true });

  for (const entry of fs.readdirSync(baseHome)) {
    if (OVERRIDDEN_ENTRIES.has(entry)) continue;
    const link = path.join(home, entry);
    const target = path.join(baseHome, entry);
    const current = readLink(link);
    if (current === target) continue;
    // Only ever replace a link we made. Refusing to unlink a real file keeps a
    // mistake in `root` from eating someone's data.
    if (current === null && fs.existsSync(link)) continue;
    try {
      fs.rmSync(link, { force: true });
      fs.symlinkSync(target, link);
    } catch {
      // A single entry that cannot be linked is not worth failing the turn
      // over; the model simply will not see that part of the home.
    }
  }

  fs.writeFileSync(
    path.join(home, "config.toml"),
    "# Generated by StagePass. Do not edit.\n"
    + "#\n"
    + "# This home exists to run stages whose contract is a line protocol, so it\n"
    + "# deliberately advertises no StagePass plugins: a model offered a card\n"
    + "# will use the card instead of writing the protocol.\n"
    + "#\n"
    + "# Everything else is symlinked back to the real Codex home, including the\n"
    + "# thread store, so turns run here stay visible in Codex Desktop.\n",
    "utf8",
  );
  return home;
}

function readLink(link: string): string | null {
  try {
    return fs.readlinkSync(link);
  } catch {
    return null;
  }
}
