import { afterEach, beforeEach, describe, it } from "node:test";

import assert from "node:assert/strict";
import { execSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { suggestCommitMessage } from "./commit-message-service.ts";

describe("commit-message-service", () => {
  let repoPath: string;
  let fakeCodexPath: string;
  let originalCodexBin: string | undefined;

  beforeEach(() => {
    repoPath = fs.mkdtempSync(path.join(os.tmpdir(), "commit-message-service-"));
    execSync("git init -b main", { cwd: repoPath, stdio: "ignore" });
    execSync("git config user.email test@example.com", { cwd: repoPath });
    execSync("git config user.name 'Test User'", { cwd: repoPath });
    fs.writeFileSync(path.join(repoPath, "app.txt"), "initial\n");
    execSync("git add app.txt", { cwd: repoPath });
    execSync("git commit -m init", { cwd: repoPath, stdio: "ignore" });
    fs.writeFileSync(path.join(repoPath, "app.txt"), "changed\n");

    fakeCodexPath = path.join(repoPath, "fake-codex.sh");
    fs.writeFileSync(
      fakeCodexPath,
      `#!/bin/sh
set -eu
out_file=
while [ "$#" -gt 0 ]; do
  if [ "$1" = "--output-last-message" ]; then
    out_file="$2"
    shift 2
    continue
  fi
  shift
done
cat >/dev/null
if [ "\${STAGEPASS_TEST_CODEX_FAIL:-0}" = "1" ]; then
  exit 1
fi
printf '%s\\n' 'feat: generated by codex' > "$out_file"
`,
      { mode: 0o755 },
    );

    originalCodexBin = process.env.STAGEPASS_CODEX_BIN;
    process.env.STAGEPASS_CODEX_BIN = fakeCodexPath;
    delete process.env.STAGEPASS_TEST_CODEX_FAIL;
  });

  afterEach(() => {
    if (originalCodexBin === undefined) {
      delete process.env.STAGEPASS_CODEX_BIN;
    } else {
      process.env.STAGEPASS_CODEX_BIN = originalCodexBin;
    }
    delete process.env.STAGEPASS_TEST_CODEX_FAIL;
    fs.rmSync(repoPath, { recursive: true, force: true });
  });

  it("reads the final message written by codex exec", async () => {
    assert.equal(await suggestCommitMessage(repoPath), "feat: generated by codex");
  });

  it("falls back when codex exec exits unsuccessfully", async () => {
    process.env.STAGEPASS_TEST_CODEX_FAIL = "1";

    assert.equal(await suggestCommitMessage(repoPath), "chore: update 2 files");
  });
});
